@startuml
left to right direction




rectangle "E-Learning App" {
    actor USER 
    actor TEACHER
    actor ADMIN
 usecase "Browse Courses" as UC1
  usecase "Enroll in Course" as UC2
  usecase "View Lessons" as UC3
  usecase "Take Quiz" as UC4
  usecase "Participate in Forum" as UC5
  usecase "Manage Courses" as UC6
  usecase "Create Lesson" as UC7
  usecase "Create Quiz" as UC8
  usecase "Manage Forum" as UC9
  usecase "Manage Users" as UC10

  USER --> UC1
  USER --> UC2
  USER --> UC3
  USER --> UC4
  USER --> UC5

  TEACHER --> UC3
  TEACHER --> UC4
  TEACHER --> UC6
  TEACHER --> UC7
  TEACHER --> UC8

  ADMIN --> UC6
  ADMIN --> UC7
  ADMIN --> UC8
  ADMIN --> UC9
  ADMIN --> UC10

  UC1 .> (View Course Details):extend
  UC2 <.left. (Enroll):include
  UC3 .> (Access Lesson Content):extend
  UC5 .> (Participate in Discussions):extend
  UC6 <. (Add Course):include
  UC7 <. (Add Lesson):include
  UC8 <. (Add Quiz):include
  UC9 <. (Moderate Forum):include
  UC10 <. (Add User):include
}


@enduml
